[colors]
foreground    = "#54433A"
background    = "#F1F1F1"
cursor_bg     = "#54433A"
cursor_border = "#54433A"
cursor_fg     = "#F1F1F1"
selection_bg  = "#D9D3CE"
selection_fg  = "#54433A"
ansi = [
  "#E9E1DB",
  "#BF0021",
  "#3A684A",
  "#A06D00",
  "#465AA4",
  "#904180",
  "#3D6568",
  "#7D6658"
]
brights = [
  "#A98A78",
  "#BC5C00",
  "#6E9B72",
  "#CCA478",
  "#7892BD",
  "#BE79BB",
  "#739797",
  "#54433A"
]
